### ISSUE TITLE
Problems with notifications on the website

### ISSUE THREAD

**Issue by AimarPaolo** [polito/nuova-pagina-studenti#90]
Everytime I open the website, the notificiations I have already read are like unread. I have to open again the tab and to click again on them in order to delete the number shown in the image below (and when I open again the site I find the same situation again) . 

<img width="145" height="77" alt="Image" src="https://github.com/user-attachments/assets/b96cf019-fbaa-498a-a88c-8c0ffb75d3e4" />

**Comment by andreaappendino** [comment]
thanks for your feedback, the issue has been fixed.

**Comment by AimarPaolo** [comment]
the problem persist when i open a course (ex. i open the webpage, i read all the notifications and then when I move in a course page the "Questionario Post Esame" notifications are again unread).
